texto-centralizado
titulo-centralizado
titulo-branco
titulo-vermelho
titulo-vermelho
texto-branco
titulo-amarelo
texto-amarelo
titulo-chumbo
texto-chumbo
fundo-verde 
fundo-amarelo 
fundo-azul
fundo-vermelho
fundo-tomate
fundo-tomate
fundo-chumbo
fundo-prata
fundo-#5499C7
fundo-#e9ecef
bloco-verde
bloco-amarelo
bloco-vermelho
bloco-chumbo 
fundo-transparent 
fundo-branco 
fundo-azul-claro